model:
  arch: minigpt4
  model_type: pretrain_vicuna0
  max_txt_len: 100
  end_sym: "###"
  q_former_model: "/mnt/disk1/liushijie/Process/CytoGPT/MiniGPT-4_Cyto-result/Q-former_stage2/20241024100/checkpoint_047.pth"
  freeze_qformer: True
#  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: "/mnt/disk1/liushijie/Process/CytoGPT/MiniGPT-4_Cyto-result/minigpt4_stage1/20241024194/checkpoint_099.pth" # linear layer 
datasets:
  cyto_vqa:
    batch_size: 4  # 6  
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
        max_words: 60

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6
  accum_grad_iters: 4 #default set to 1 , custom setting
  weight_decay: 0.05
  max_epoch: 100
  log_freq: 50  # train loss visible frequency

  iters_per_epoch: 1520  # dataset 36468 sfy1 sfy2 20x_sfy3
  num_workers: 3
  warmup_steps: 15200

  seed: 42
  output_dir: "/mnt/disk1/liushijie/Process/CytoGPT/MiniGPT-4_Cyto-result/minigpt4_autoPrompt_finetune" 

  amp: True
  resume_ckpt_path: null

  evaluate: False    # set to True to skip training
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name:  CytoGPT_autoPrompt_stage2_fintune_W_categoy2

